import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Section from "./components/Section";
import Page from "./page";
import Slider from "./components/Slider";
import Footer from "./components/Footer";
import Selector from "./components/Selector";
import Sector from "./components/Sector";
// import LoginPage from "./components/Login";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Page />
        <br />
        <br />
        <br />
        <Slider />
        {/* <LoginPage /> */}
        <br />
        <Selector />
        <br />
        <Section />
        {/* <Footer /> */}
        <br />
        <br />
        <Sector />

      </body>
    </html>
  );
}